Add tag with Polarion test case to DW test
red-hat-data-services/ods-ci pull request #1024
Opened 2023-11-16 12:52 UTC by jiripetrlik

2023-11-16 13:47 UTC, aloganat submitted a review, later dismissed

2023-11-16 13:53 UTC, bdattoma submitted a review, later dismissed

2023-11-21 10:49 UTC, jgarciao requested changes

2023-11-21 10:49 UTC, jgarciao commented on ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
> +    [Tags]  ODS-2511
Can you also add TierX tag?

2023-11-21 10:49 UTC, jgarciao commented on ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
>      Skip If    "%{OPERATOR_TYPE}" != "RHODS Operator V2"
Can you use the new keyword  `Skip If Component Is Not Enabled` introduced in #1010

2023-11-21 11:46 UTC, jiripetrlik commented
@jgarciao Thank you for the review. I've added Tier1 tag. Yes, I will use "Skip If Component Is Not Enabled" when it is available.

2023-11-21 11:48 UTC, jstourac commented
> @jgarciao Thank you for the review. I've added Tier1 tag. Yes, I will use "Skip If Component Is Not Enabled" when it is available.

#1010 just got merged JFYI.

2023-11-21 14:24 UTC, jgarciao approved these changes

2023-11-21 14:50 UTC, asanzgom approved these changes

2023-11-21 14:57 UTC, merged