Keywords for management of components
red-hat-data-services/ods-ci pull request #1085
Opened 2023-12-18 16:15 UTC by jiripetrlik

2023-12-19 08:19 UTC, sutaakar approved these changes
Looks good to me

2024-01-04 08:48 UTC, sutaakar submitted a review, later dismissed

2024-01-04 09:10 UTC, jstourac commented
LGTM, one proposal for an improvement would be to unify the code - so these two keywords would use one common implementation by addition also the `operation` parameter. WDYT @jiripetrlik ?

2024-01-04 15:27 UTC, jstourac commented on ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
> +    ${result} =    Run Process    oc patch ${cluster_name} --type 'json' -p '[{"op" : "replace" ,"path" : "/spec/components/${component}/managementState" ,"value" : "${component}"}]'
```suggestion
    ${result} =    Run Process    oc patch ${cluster_name} --type 'json' -p '[{"op" : "replace" ,"path" : "/spec/components/${component}/managementState" ,"value" : "${state}"}]'
```

2024-01-04 15:28 UTC, jstourac requested changes
One comment, otherwise LGTM.

2024-01-04 16:10 UTC, jstourac approved these changes
LGTM, once tested properly (could you please share a CI?) I'm all for merge this.

2024-01-04 16:19 UTC, jiripetrlik commented
I was able to successfully run this with Jenkins. @sutaakar @jstourac @jgarciao Can we merge now?

2024-01-05 08:27 UTC, sutaakar approved these changes

2024-01-05 09:34 UTC, jgarciao approved these changes

2024-01-05 09:34 UTC, merged