RHOAIENG-6517 Automate support for configuration of controller resources
red-hat-data-services/ods-ci pull request #1515
Opened 2024-06-11 11:22 UTC by asanzgom

2024-06-11 12:53 UTC, asanzgom commented
rhods-ci-pr-test/2959 ran successfully

2024-06-12 09:37 UTC, FedeAlonso requested changes

2024-06-12 09:41 UTC, asanzgom commented on ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
> +        ${sa_name}=    Set Variable    ${d_obj_dictionary.spec.template.spec.serviceAccountName}
@FedeAlonso Can you explain this requested change? Is it formatting?

2024-06-12 13:09 UTC, FedeAlonso commented on ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
> +        ${sa_name}=    Set Variable    ${d_obj_dictionary.spec.template.spec.serviceAccountName}
No, it's just that that variable is not used (maybe I'm wrong)

2024-06-12 13:11 UTC, FedeAlonso approved these changes

2024-06-12 13:44 UTC, asanzgom commented on ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
> +        ${sa_name}=    Set Variable    ${d_obj_dictionary.spec.template.spec.serviceAccountName}
Removed

2024-06-12 14:09 UTC, CFSNM approved these changes
LGTM

2024-06-12 14:18 UTC, FedeAlonso approved these changes

2024-06-12 14:18 UTC, merged