Create IDE test suite directory with proper nested suites
red-hat-data-services/ods-ci pull request #1562
Opened 2024-06-26 13:31 UTC by bdattoma

2024-06-26 15:05 UTC, jiridanek requested changes
> move the test suites of ISVs related to IDEs (i.e., Anaconda, Openvino, Aikit, Watson Studio)

@harshad16, @atheo89 are we responsible for these, as IDE team? I never really touched them. If it's not our purview, then they should be placed somewhere else.

The docs are https://www.redhat.com/en/resources/openshift-data-science-overview#section-4 and https://catalog.redhat.com/solutions/detail/5d6a4953195a4114a6136fb63206d540 and the Resources tab https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.8/html/getting_started_with_red_hat_openshift_ai_self-managed/tutorials-for-data-scientists_get-started

2024-06-26 15:57 UTC, harshad16 commented
There is no clear direction of ISV , it is hard to comment on this.

2024-06-27 07:37 UTC, bdattoma commented
> > move the test suites of ISVs related to IDEs (i.e., Anaconda, Openvino, Aikit, Watson Studio)
> 
> @harshad16, @atheo89 are we responsible for these, as IDE team? I never really touched them. If it's not our purview, then they should be placed somewhere else.
> 
> The docs are https://www.redhat.com/en/resources/openshift-data-science-overview#section-4 and https://catalog.redhat.com/solutions/detail/5d6a4953195a4114a6136fb63206d540 and the Resources tab https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.8/html/getting_started_with_red_hat_openshift_ai_self-managed/tutorials-for-data-scientists_get-started


The concept is that these ISVs I moved under IDE folder are themselves IDEs or Jupyter images, hence they would logically fall under IDE scope in my opinion

2024-06-27 12:30 UTC, jiridanek approved these changes

2024-06-28 09:24 UTC, jgarciao approved these changes

2024-06-28 09:27 UTC, merged