KFP as a smoke test
red-hat-data-services/ods-ci pull request #1595
Opened 2024-07-03 13:48 UTC by diegolovison

Pipelines team are now represented by two teams. Backend and Frontend This ensure that only the backend will run during the nightly builds

2024-07-04 07:40 UTC, jgarciao commented on ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
> +    [Tags]      Smoke    ODS-2203
It should have Smoke and Tier1 tags

2024-07-04 07:43 UTC, jgarciao requested changes

2024-07-04 07:43 UTC, jgarciao commented on ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
> +    [Tags]        Smoke    ODS-2683
I think this one should be in Sanity (it should have Sanity & Tier1 tags)

2024-07-04 07:43 UTC, jgarciao commented on ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
> -    [Tags]      Tier1
I think this test is fine in Tier1

2024-07-04 13:16 UTC, jgarciao approved these changes

2024-07-05 06:13 UTC, FedeAlonso approved these changes

2024-07-05 07:27 UTC, merged