No cache for iris pipelines steps and pipeline_root
red-hat-data-services/ods-ci pull request #1605
Opened 2024-07-05 11:31 UTC by diegolovison

No cache for iris pipelines steps and pipeline_root

Please keep the two commits.
Tested locally on RHOAI 2.11

2024-07-05 12:05 UTC, jgarciao requested changes

2024-07-05 12:05 UTC, jgarciao commented on ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap.py
Can you create a different pipeline sample for this (e.g. iris_pipeline_custom_pipeline_root.py)?

2024-07-05 12:18 UTC, diegolovison commented on ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap.py
Done. Created different pipelines

2024-07-05 15:35 UTC, jgarciao approved these changes

2024-07-09 13:57 UTC, CFSNM approved these changes

2024-07-09 14:24 UTC, merged