Disable Platform ModeRegistry Tests On RHOAI
red-hat-data-services/ods-ci pull request #1742
Opened 2024-08-21 18:13 UTC by mattmahoneyrh

Added excludeOnRHOAI tag on ModelRegistry test cases so that they are not run on RHOAI.

2024-08-21 18:34 UTC, CFSNM approved these changes

2024-08-22 10:36 UTC, CFSNM requested changes

2024-08-22 10:36 UTC, CFSNM commented on ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
> +    [Tags]    Operator    Tier1    RHOAIENG-10404    modelregistry-managed    excludeOnRHOAI
not sure if the tag is case-sensitive, but in the jobs we use ExcludeOnRHOAI tag

2024-08-22 12:01 UTC, CFSNM approved these changes

2024-08-22 12:14 UTC, asanzgom approved these changes

2024-08-22 12:18 UTC, closed without merging