Add initial upgrade testing for Data Science Pipelines
red-hat-data-services/ods-ci pull request #1869
Opened 2024-09-30 11:56 UTC by jgarciao

Adds initial upgrade testing for Data Science Pipelines, creating a pipeline server and starting a long running pipeline, and checking the status after upgrade

Note: additional scenarios, like setting up an scheduled run before upgrade, will be covered in follow-up PRs

2024-09-30 12:39 UTC, diegolovison approved these changes

2024-09-30 13:27 UTC, FedeAlonso requested changes

2024-09-30 13:27 UTC, FedeAlonso commented on ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
> +Get Dsp Version
```suggestion
Get DSP Version
```

2024-09-30 13:27 UTC, FedeAlonso commented on ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
> +    ${dspVersion}=    Get Dsp Version    ${namespace}
```suggestion
    ${dspVersion}=    Get DSP Version    ${namespace}
```

2024-09-30 13:27 UTC, FedeAlonso commented on ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
> +    ...    Deletes ${PROJECT} if all verifications are correct (leaving for debugging purpuses if not)
```suggestion
    ...    Deletes ${PROJECT} if all verifications are correct (leaving for debugging purposes if not)
```

2024-09-30 14:46 UTC, jgarciao commented on ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
> +Get Dsp Version
Done

2024-09-30 14:46 UTC, jgarciao commented on ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
> +    ${dspVersion}=    Get Dsp Version    ${namespace}
Done

2024-09-30 14:48 UTC, diegolovison submitted a review, later dismissed

2024-09-30 14:49 UTC, FedeAlonso submitted a review, later dismissed

2024-10-01 08:35 UTC, jgarciao commented
This PR (before the latest rebase) was tested successfully in rhoai-test-flow/617

2024-10-01 09:58 UTC, FedeAlonso approved these changes

2024-10-01 12:53 UTC, diegolovison approved these changes

2024-10-01 14:25 UTC, merged