Backport "Add GPU specific Tags" PR into releases/2.10.0 branch
red-hat-data-services/ods-ci pull request #1942
Opened 2024-10-17 15:49 UTC by bdattoma

2024-10-17 16:14 UTC, diegolovison submitted a review, later dismissed

2024-10-17 16:32 UTC, jstourac submitted a review, later dismissed

2024-10-21 09:36 UTC, CFSNM submitted a review, later dismissed

2024-10-21 13:16 UTC, jstourac requested changes
@bdattoma commented [here](https://github.com/red-hat-data-services/ods-ci/pull/1943/files#r1808803025). Affects all the others maybe.

2024-10-21 13:29 UTC, jstourac approved these changes

2024-10-22 08:58 UTC, aloganat approved these changes

2024-10-22 11:19 UTC, merged