Add test cases to check error messages about RHODS groups
red-hat-data-services/ods-ci pull request #424
Opened 2022-06-21 10:51 UTC by bdattoma

This PR wants to implement automation for the following TCs:
- ODS-1408
- ODS-1494
- ODS-1495 -> it does not test "groups-config" CM because it is immediately re-created by the operator if it gets deleted. I tried catching the error message, but the re-creation is very fast and sometime the msg does not appear (it would make the test very flaky, besides deleting it wouldn't be a user-scenario.
- ODS-1500

2022-06-21 11:08 UTC, bdattoma commented
I've tested the TCs on a live build of v1.13, all of them passed successfully
![1495](https://user-images.githubusercontent.com/88311595/174785541-aeaa6945-1e1a-445d-8a26-8abe063c0a37.png)
![1500](https://user-images.githubusercontent.com/88311595/174785545-4db19428-f43b-4eca-9c29-55c76f016ba5.png)
![1494](https://user-images.githubusercontent.com/88311595/174785547-96f97c3c-aeed-4c74-ae8e-4656dd21dca0.png)
![1408](https://user-images.githubusercontent.com/88311595/174785550-2a186d42-bf45-4fd7-925c-33be5a15bf2e.png)
d

2022-06-22 08:30 UTC, lucferbux approved these changes
/lgtm

2022-06-23 09:53 UTC, jgarciao commented
Will be merged after the release of ods-ci 1.12

2022-06-23 09:57 UTC, jgarciao requested changes

2022-06-23 09:57 UTC, jgarciao commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]  Sanity
Tier1 missing

2022-06-23 09:57 UTC, jgarciao commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]  Sanity
Tier1 missing

2022-06-23 09:57 UTC, jgarciao commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]    Sanity
Tier1 missing

2022-06-23 09:57 UTC, jgarciao commented on tests/Resources/Common.robot
> +Clean Resource YAML Before Creating It
[Documentation] missing

2022-06-24 10:38 UTC, bdattoma commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]  Sanity
done

2022-06-24 10:38 UTC, bdattoma commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]  Sanity
done

2022-06-24 10:38 UTC, bdattoma commented on tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
> +    [Tags]    Sanity
done

2022-06-24 10:38 UTC, bdattoma commented on tests/Resources/Common.robot
> +Clean Resource YAML Before Creating It
done

2022-06-24 13:06 UTC, lugi0 approved these changes
a couple of style issues otherwise lgtm

2022-06-24 13:06 UTC, lugi0 commented on tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
> +Get Dashboard Pods Names
missing line break

2022-06-24 13:06 UTC, lugi0 commented on tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
> +    [Documentation]     Fetches the logs from one dashboard pod
Keyword name should be singular since it fetches the logs of only one pod

2022-06-24 13:51 UTC, lugi0 approved these changes
lgtm

2022-06-24 16:44 UTC, pablofelix approved these changes
lgtm

2022-06-28 07:25 UTC, jgarciao approved these changes
lgtm

2022-06-28 15:56 UTC, merged