JupyterLab-git_Version change from  v0.30 to  v0.32
red-hat-data-services/ods-ci pull request #499
Opened 2022-08-16 11:44 UTC by mwaykole

Signed-off-by: mwaykole <mwaykole@redhat.com>

2022-08-17 05:46 UTC, aloganat approved these changes
lgtm

2022-08-17 07:59 UTC, jgarciao requested changes

2022-08-17 07:59 UTC, jgarciao commented on tests/Tests/500__jupyterhub/test-versions.robot
> +${JupyterLab-git_Version}     v0.32
In order to support RHODS 1.14 and RHODS 1.15 (used during live testing) you can define a variable with the old value (e.g. `${JupyterLab-git_Version-legacy})` and use it with` Is RHODS Version Greater Or Equal Than`

2022-08-22 09:10 UTC, lugi0 commented
@mwaykole please check if in 1.14 the img getting pulled also includes the updated plugin. If it does I think this PR can be merged as is, otherwise I agree with Jorge

2022-11-27 15:05 UTC, closed without merging