Add product and and remove flaky test
red-hat-data-services/ods-ci pull request #572
Opened 2022-09-22 06:09 UTC by tarukumar

Signed-off-by: Tarun Kumar <takumar@redhat.com>

2022-09-22 06:26 UTC, tarukumar commented
Jenkins [job](https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1292) failed due to product bug

2022-09-23 10:47 UTC, jgarciao requested changes

2022-09-23 10:47 UTC, jgarciao commented on tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
> +  Wait Until Keyword Succeeds    10 times  5s    Click On Searched Operator      Red Hat OpenShift Data Science   #robocp: disable
typo in robocop

2022-09-23 13:05 UTC, tarukumar commented on tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
> +  Wait Until Keyword Succeeds    10 times  5s    Click On Searched Operator      Red Hat OpenShift Data Science   #robocp: disable
done

2022-09-26 05:44 UTC, mwaykole approved these changes

2022-09-27 14:16 UTC, jgarciao approved these changes
lgtm

2022-09-27 14:16 UTC, merged