Modify aws cluster config to expose variables to user
red-hat-data-services/ods-ci pull request #612
Opened 2022-11-01 19:48 UTC by aloganat

Signed-off-by: Arthy Loganathan <aloganat@redhat.com>

2022-11-03 08:00 UTC, tarukumar approved these changes
LGTM. Lets wait for the @pablofelix approval before we merge it

2022-11-10 08:59 UTC, jgarciao commented on tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
> +    name: {{ cluster_image_set|default("rhods-openshift") }}
@pablofelix Is there a way to populate the same variable in two places?

2022-11-10 12:54 UTC, pablofelix requested changes
Variable cluster_image_set should have the same value as the base_image_set. It could be better to use only one variable image_set for example instead

2022-11-10 13:01 UTC, aloganat commented
> 

Hi @pablofelix , As I have mentioned in the call, if I use the same variable for example image_set, its not been substituted in both the places - https://github.com/aloganat/ods-ci/blob/aws_config_hive/tasks/Resources/Provisioning/Hive/AWS/oc-provision.robot#L8 . Could you let me know if there is a way to do it?

2022-11-11 08:22 UTC, pablofelix approved these changes
lgtm

2022-11-11 08:50 UTC, jgarciao approved these changes

2022-11-11 09:03 UTC, merged