Fix Pachyderm links
red-hat-data-services/ods-ci pull request #712
Opened 2023-03-09 12:12 UTC by diegolovison

2023-03-09 12:44 UTC, bdattoma commented
Although the new links look good, I would wait to receive a confirmation about the desired links to use, because the same wrong ones are present in RHODS: RHODS-7424.

2023-03-09 12:54 UTC, diegolovison commented
https://github.com/red-hat-data-services/odh-deployer/pull/310

2023-03-10 18:26 UTC, jgarciao approved these changes
lgtm

2023-04-27 14:47 UTC, bdattoma submitted a review, later dismissed

2023-04-27 14:48 UTC, bdattoma commented
please run the PR test in Jenkins

2023-04-28 07:37 UTC, bdattoma requested changes

2023-04-28 07:37 UTC, bdattoma commented on ods_ci/tests/Resources/Files/AppsInfoDictionary.json
>                     "9": {
these changes are not required, only the json file with _latest suffix should be changed. This one is used for retrocompatibility with previous version of RHODS

2023-04-28 16:06 UTC, bdattoma approved these changes

2023-05-02 18:28 UTC, diegolovison commented
It worked https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1716/robot/report/files/test_report.html
I removed later the `ProductBug`

2023-05-03 07:35 UTC, bdattoma approved these changes

2023-05-03 13:25 UTC, jgarciao approved these changes

2023-05-03 13:25 UTC, merged