[RHODS-7871] ODS-395 Verify App name
red-hat-data-services/ods-ci pull request #738
Opened 2023-04-05 03:35 UTC by nehachopra27

Automate https://polarion.engineering.redhat.com/polarion/#/project/OpenDataHub/workitem?id=ODS-395

2023-04-11 12:12 UTC, nehachopra27 commented
**Tests**: https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1659/console

Passing

2023-04-11 12:14 UTC, jgarciao requested changes

2023-04-11 12:14 UTC, jgarciao commented on ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
> +    ...       Tier1    xxxx
xxxx should be removed

2023-04-11 12:14 UTC, jgarciao commented on ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
> +        Should Be True	${length} > 5
You can also use `Should Start With` to verify that the app name  starts with _by_ and also use [Remove String](https://robotframework.org/robotframework/latest/libraries/String.html#Remove%20String) to get it removed from the  string and obtain the app name

2023-04-11 14:30 UTC, jgarciao approved these changes
lgtm

2023-04-12 08:43 UTC, bdattoma approved these changes

2023-04-12 16:15 UTC, merged