Select Pipeline name (if applicable) when navigating to Create Run page
red-hat-data-services/ods-ci pull request #811
Opened 2023-06-06 17:13 UTC by diegolovison

2023-06-07 04:02 UTC, mwaykole approved these changes

2023-06-07 08:04 UTC, bdattoma commented on ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
> +    [Arguments]    ${name}    ${pipeline_name}    ${from_actions_menu}    ${from_actions}=${TRUE}
what's the difference btw these 2 arguments?

2023-06-07 08:05 UTC, bdattoma commented on ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
> +    ...    cron_expr=${cron_expr}    &{model_param}    from_actions_menu=${from_actions_menu}
the argument is not used in the code of this keyword. could you remove it?

2023-06-07 08:07 UTC, bdattoma requested changes

2023-06-07 08:07 UTC, bdattoma commented on ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
> +    ...    cron_expr=${cron_expr}    &{model_param}    from_actions_menu=${from_actions_menu}
the argument is not used in the code of this keyword. could you remove it?

2023-06-07 08:07 UTC, bdattoma commented on ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
> +    IF    ${from_actions_menu} == ${FALSE}
does the issue happens only when creating the run not from the actions menu?

2023-06-07 08:13 UTC, bdattoma commented on ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
> +        Select Pipeline For The Run    pipeline_name=${pipeline_name}
hm probably, in order to warn when the issue happens, we could use a different flow like:

```
IF ${GENERIC_CREATE_BTN_XP} is enabled when it should not
THEN raise a WARN message and Wait until the dropdown gets the value
```

2023-06-08 07:37 UTC, bdattoma approved these changes

2023-06-08 07:49 UTC, jgarciao approved these changes

2023-06-08 07:50 UTC, jgarciao approved these changes

2023-06-08 12:39 UTC, diegolovison commented
https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhods-ci-pr-test/1853/robot/report/files/test_report.html

2023-06-08 12:54 UTC, merged