Update Smoke Suite
red-hat-data-services/ods-ci pull request #948
Opened 2023-09-22 15:54 UTC by lugi0

2023-09-22 16:08 UTC, diegolovison approved these changes

2023-09-25 07:53 UTC, bdattoma requested changes

2023-09-25 07:53 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
> +    [Tags]    Smoke    ODS-1812
please remove this from smoke because it gets skipped from RHODS 1.20 on. We can remove the test from the suite at all

2023-09-25 07:53 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
> +    [Tags]    Smoke    ODS-1812
let's add ODS-1814 instead

2023-09-25 07:53 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
> +    [Tags]    Smoke    ODS-1817
this test case fails without ODS-1816

2023-09-25 07:53 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
> +    [Tags]    Smoke    ODS-1815
fails without ODS-1814

2023-09-25 07:53 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
>  Verify User Can Delete A Data Science Project
we could add `ODS-1813 Verify User Can Delete A Workbench`

2023-09-25 08:22 UTC, bdattoma submitted a review, later dismissed

2023-09-26 12:53 UTC, jgarciao approved these changes

2023-09-26 13:01 UTC, aloganat approved these changes
lgtm

2023-09-26 15:58 UTC, merged