Add runtime image upgrade test
red-hat-data-services/ods-ci pull request #975
Opened 2023-10-10 15:12 UTC by bdattoma

This PR wants to ensure that if the Caikit+TGIS runtime gets upgraded, the already deployed models don't get affected by the upgrade. 

1. it deploys a model
2. it changes the image URL
3. checks that there is still one pod running
4. checks the creation date of the pod remains unchanged (i.e., no restarts after runtime upgrade)
5. checks the image URL used by the running pod didn't change

2023-10-17 05:46 UTC, FedeAlonso submitted a review, later dismissed
LGTM

2023-10-17 11:54 UTC, jgarciao submitted a review, later dismissed

2023-10-19 14:26 UTC, FedeAlonso commented on ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
> +    [Arguments]    ${new_image_url}    ${model_name}    ${namespace}
@bdattoma  have you checked this alert?  '${model_name}'  is not used

2023-10-19 14:28 UTC, FedeAlonso commented on ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
> +    ${rc}    ${out}=    Run And Return Rc And Output
@bdattoma And this one too.  '${out}' is assigned but not used

2023-10-19 14:46 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
> +    ${rc}    ${out}=    Run And Return Rc And Output
I think this one is ok to leave as it is, because ${out} variable would help during debugging in case of failures.

2023-10-20 04:57 UTC, FedeAlonso requested changes

2023-10-20 04:57 UTC, FedeAlonso commented on ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
> +Get Model Pods Creation Date And Image URL
Doc here?

2023-10-20 07:54 UTC, bdattoma commented on ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
> +Get Model Pods Creation Date And Image URL
there is the documentation, line 888

2023-10-23 08:05 UTC, jgarciao approved these changes

2023-10-23 08:24 UTC, FedeAlonso approved these changes

2023-10-23 08:41 UTC, merged